depromeet12th/three-days-android

- domain/src/main/java/com/depromeet/threedays/domain/MyClass.kt
- domain/src/main/java/com/depromeet/threedays/domain/entity/Goal.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/GoalRepository.kt
- 목표 생성/수정/삭제에 대한 비즈니스 로직을 작성했습니다
1. 서버에선 `endTime`이라고 수행종료시간도 있던데, 화면상에선 필요하지 않는 부분이라 넣지 않았습니다
2. push알림에 관련한 변수들(notificationTime, notificationContent) 또한 서버 측에선 사용하지 않았지만, UT 화면상에선 필요해서 넣었습니다.
-> 1,2 번에 관련한 사항은 추후 수정하거나 해성님이 작성하다가 변경이 필요하시면 변경해주시면 될 것 같습니닷..!
3. 꼭 입력이 필요하지 않은 필드의 값을 null로 처리할지, 아니면 "" 와 같이 빈 텍스트로 넘겨줄지에 대한 논의도 필요할 것 같습니다
> DEP-56 feat: 목표 생성/수정/삭제에 대한 Repository 작성

- data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
- data/src/main/java/com/depromeet/threedays/data/repository/GoalRepositoryImpl.kt
- data/src/main/java/com/depromeet/threedays/data/repository/LocalGoalRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/GoalRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/CreateGoalUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/UpdateGoalUseCase.kt
- 이름 변경 (LocalGoalRepository -> GoalRepositoryImpl)
- 타입 변경 (String -> ZonedDateTime? = null)
> DEP-58 refactor: 리뷰 반영

- domain/src/main/java/com/depromeet/threedays/domain/usecase/DeleteUseCase.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
- 목표 삭제가 불가능 했습니다.
- 이제 목표 삭제가 가능합니다.
실시간 반영은 아직 해결을 못했으니 삭제 후 다른 탭으로 갔다가 돌아오셔야 합니다.
+) 토스트 메시지 커스텀은 혜인님 부탁드립니당
> DEP-87 feat: 목표 삭제 기능 구현

- presentation/home/src/main/java/com/depromeet/threedays/home/home/CompleteGoalDialog.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- 3일 째 달성해도 아무런 효과가 없었습니다.
3일 목표를 달성하면 저걸 다 리셋 시켜야 하는지 애매하네요. 협의가 안된 부분 같은데
1일차 2일차는 활성화 취소 가능하게 하고 3일차는 바로 리셋되게 해서 취소가 불가능하게 할건지
리셋 된다면 3개 다 손 접어있는 상태 + 파란색 테두리가 없는 상태인건지 등...
우선 내일 제가 첫 출근이라 시간이 없을까봐 여기까지 강제로 머지해둡니다 ㅠ
> feat: 3일 목표 달성 다이얼로그 연동

- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/ConnectHabitFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/ConnectHabitViewModel.kt
- presentation/mate/src/main/res/layout/fragment_connect_habit.xml
- presentation/mate/src/main/res/layout/item_habit.xml
- presentation/mate/src/main/res/values/strings.xml
음.. 특이사항은 없고 `tools:ignore="TypographyFractions"` 이거는
"너 1/3 왜 써 ⅓ 이거 쓰려는 거 아냐?"
라고 경고 띄워서 무시하기 설정했습니다.
> DEP-170 짝꿍 만들기 1단계 UI 구현

- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewMoodel.kt
- presentation/mate/src/main/res/drawable/bg_rect_gray100_border_gray300_r10.xml
- presentation/mate/src/main/res/drawable/selector_edittext.xml
- presentation/mate/src/main/res/layout/fragment_set_mate_nickname.xml
- presentation/mate/src/main/res/values/strings.xml
editText 입력 값에 따른 ui 변화는 기능 구현할 때 같이 넣을 예정입니다.
그 외 기본 ui 베이스를 구현해두었습니다.
> DEP-187 ui: 짝꿍 만들기 3단계 UI 구현

- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/res/layout/fragment_mate.xml
- presentation/mate/src/main/res/values/strings.xml
커밋의 단위가 작은 건 좋지만
PR의 단위가 작으면 안 좋은가...? 싶기도 하고... (저는 안 귀찮은데 두 분이 귀찮으실까봐...)
어떠신가요??
네.. 아무튼 사소한 ui 구현 PR 입니당
> DEP-194 ui: 짝꿍 페이지 툴팁과 디폴트 화면 구현

- data/src/main/java/com/depromeet/threedays/data/api/HabitService.kt
- data/src/main/java/com/depromeet/threedays/data/api/interceptor/AuthInterceptor.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
- data/src/main/java/com/depromeet/threedays/data/entity/base/ApiResponse.kt
- base url이 짝심삼일 서버 url이 아니었습니다.
- base url을 짝심삼일 url 로 변경했습니다
- 헤더에 임시 토큰을 넣었습니다
- base response를 제작했습니다.
- AuthInterceptor에 아직은 토큰의 유효성을 검증하는 작업 코드는 안넣었습니당... 일단은 먼저 올리고 추후에...
> DEP-210 feat: 서버 연결 초기 세팅

- .github/workflows/build.yml
- gradle wrapper 직접 사용해서 빌드
- gradle build action 사용해서 빌드
- 로그가 2,000 라인 정도로 줄었습니다. 
- 왜 동작이 다른지는 잘 모릅니다 ㅠ.ㅠ
> DEP-000 config: gradle build action 적용

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitAdapter.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewHolder.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/archived_mate/ArchivedMateUI.kt
- 짝궁 이미지 누르면 dialog 가 나옵니다.
- imageUrl 에 어떤값 넣어야할지 모르겠어요
- 짝궁성격, 레벨마다 이미지 구분하는걸 서버/클라이언트 어느쪽에서 하기로했는지 기억이 안나서 하드코딩 해두었습니다. api 연동하면서 다시 확인해볼게요
---
> DEP-207 feat: 짝궁 이미지 누르면 dialog 표시

- data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
> DEP-000: 서브 도메인으로 변경

- data/src/main/java/com/depromeet/threedays/data/api/MemberService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/di/RemoteModule.kt
- data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
- data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
- data/src/main/java/com/depromeet/threedays/data/entity/member/MemberEntity.kt
- data/src/main/java/com/depromeet/threedays/data/mapper/MemberMapper.kt
- data/src/main/java/com/depromeet/threedays/data/repository/MemberRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/entity/member/AuthenticationProvider.kt
- domain/src/main/java/com/depromeet/threedays/domain/entity/member/Member.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/MemberRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/GetMyInfoUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageViewModel.kt
- presentation/mypage/src/main/res/layout/fragment_my_page.xml
- 닉네임 하드코딩
- 내 정보 조회 API 의 name 값 사용
- API 연동시 loading, error 처리는 아직 안했습니다 ㅠ.ㅠ
> DEP-247 feat: 내 정보 조회 API 연동

- data/src/main/java/com/depromeet/threedays/data/api/HabitService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/habit/HabitRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/repository/HabitRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/HabitRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/habit/DeleteArchivedHabitUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewModel.kt
- 보관된 습관 삭제 API 연동 (`DELETE /api/v1/habits/{habitId}`)
> feat: 보관된 습관 삭제 API 연동

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/depromeet/threedays/firebase/FCMService.kt
- app/src/main/java/com/depromeet/threedays/firebase/FirebaseModule.kt
- app/src/main/java/com/depromeet/threedays/license/LicenseNavigatorImpl.kt
- app/src/main/java/com/depromeet/threedays/license/NavigatorModule.kt
- build.gradle
- dependencies.gradle
- navigator/src/main/java/com/depromeet/threedays/navigator/LicenseNavigator.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/res/layout/fragment_my_page.xml
- presentation/mypage/src/main/res/values/strings.xml
- 오픈소스 라이선스 페이지 추가
- release 로 빌드해야 목록이 제대로 나오나봐요
- com.android.application 플러그인 적용된 모듈에 오픈소스 라이선스 플러그인도 추가해야해서, app 모듈에 추가했습니다. 그래서 다른 Navigator-impl 과 다른구조로 파일 배치되어있습니다. 의견 부탁드려요
| 마이페이지 | 오픈소스 라이선스 페이지 |
|-|-|
| <img width="405" alt="image" src="https://user-images.githubusercontent.com/4813025/209650052-27bb8cb7-0817-4c3b-b855-ff5957f2c001.png"> | <img width="410" alt="image" src="https://user-images.githubusercontent.com/4813025/209650445-db81ad1f-9335-46e9-89a5-c9ac84d93d3c.png">|
> DEP-303 feat: 오픈소스 라이선스 페이지 추가

- app/src/main/AndroidManifest.xml
- data/src/main/java/com/depromeet/threedays/data/api/MateService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/mate/MateRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/entity/mate/PostMateRequest.kt
- data/src/main/java/com/depromeet/threedays/data/repository/MateRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/entity/mate/CreateMate.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/MateRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/mate/CreateMateUseCase.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewModel.kt
- 짝꿍 만들기 api 구현 및 연동
- 생성시 액티비티 한번에 pop 하여 원래 페이지로 돌아가도록 설정
현재 api에 문제가 있는듯함
수정된 후 재확인 필요
> DEP-215 feat: 짝꿍 만들기 기능 구현

- .github/workflows/deploy.yml
- domain/src/main/java/com/depromeet/threedays/domain/entity/DataState.kt
- domain/src/main/java/com/depromeet/threedays/domain/entity/HabitStatus.kt
> DEP-308 config: keystore 파일 추가

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/policy/src/main/res/layout/activity_policy.xml
- 임시 url
- notion 공유 링크
- DNS 적용되면 주소 변경할 예정입니다
- debug, release 빌드 환경따라 변수 변경할 예정입니다
> DEP-301 feat: 이용약관, 개인정보처리방침 url 추가

- core-design-system/src/main/res/values/typography.xml
- Typography.Body4 에 fontFamily 추가
> DEP-312 fix: fontFamily 추가

- presentation/mate/src/main/res/layout/fragment_mate.xml
xml에는 background로 기본값넣고
코드에서는 src로 넣어서
캐릭터 2개가 겹쳐 보이는 버그가 있어 수정했습니다.
> DEP-320 fix: 캐릭터가 중첩되어 보이는 버그 수정

- presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingActivity.kt
https://user-images.githubusercontent.com/76620764/209995965-b4dff772-9d6b-42a7-abac-d75157c98c61.mp4
텍스트 할당하는 로직을 이상한 위치에 가져다 놨었네요...
급하게 짜다보니 놓친게 많네요 ㅠㅠ
> DEP-323 fix: 온보딩 (스플래시 이후) 버튼 텍스트가 이상한 문제 해결

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
- presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationHistoryActivity.kt
> DEP-313 feat: 뒤로 버튼 핸들러 추가

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- app/build.gradle
- core-design-system/build.gradle
- core/build.gradle
- data/build.gradle
- navigator/build.gradle
- presentation/create/build.gradle
- presentation/history/build.gradle
- presentation/home/build.gradle
- presentation/mate/build.gradle
- presentation/mypage/build.gradle
- presentation/notification/build.gradle
- presentation/onboarding/build.gradle
- presentation/policy/build.gradle
- presentation/signup/build.gradle
- presentation/splash/build.gradle
- GitHub Secret 에 올린 debug.keystore 파일 사용해서 signing 이 잘되어야함. 
buildType 아래처럼 나눠볼려고합니다. 의견주세요! 
- debug : 로컬
- alpha : firebase app distribution
- beta : google play store beta program (?)
- release : 운영
> DEP-308 config: buildType alpha 추가

- .github/workflows/deploy.yml
- app/build.gradle
- debug.keystore 파일 크기가 0이었음
- 파일 내용 포함해서 잘 만들도록 변경
- app-alpha.apk 로 파일 경로 변경
> DEP-000 config: 앱 signing 실패하는 현상 해결

- presentation/mypage/src/main/res/layout/fragment_edit_nickname_dialog.xml
- 스타일 누락됨
- textApperance, textColor 적용
> DEP-326 fix: 닉네임 dialog text style 적용

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- build.gradle
- 버전코드 2 하드코딩
- develop 에 머지된 코드가 `deploy.yml` 으로 배포될 때, 공용계정 이름으로 버전 올리는 코드 커밋 추가함
> DEP-36 config: Add version code automatically

- core/src/main/java/com/depromeet/threedays/core/BaseViewModel.kt
- data/src/main/java/com/depromeet/threedays/data/api/interceptor/AuthInterceptor.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/ThreeDaysSharedPreference.kt
- data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
- data/src/main/java/com/depromeet/threedays/data/repository/AuthRepositoryImpl.kt
- data/src/main/java/com/depromeet/threedays/data/repository/MemberRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/AuthRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/MemberRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/LogoutUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/WithdrawUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageViewModel.kt
- 로그아웃, 회원탈퇴시 토큰 삭제
- baseViewModel 기본에러메시지 임시로 추가했습니다. 'null' 이나 '' 보다는 뭐라도 써있는게 좋을거같아서요. 
- Authorization 헤더도 로그에 남기고싶어서 retrofit loggingInterceptor 순서 바꿨습니다.
> DEP-287 feat: 로그아웃, 회원탈퇴시 토큰 삭제

- domain/src/main/java/com/depromeet/threedays/domain/util/GetDateTimeFromString.kt
- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
- presentation/history/src/main/res/layout/fragment_history.xml
https://user-images.githubusercontent.com/76620764/210127000-b675feef-ab3f-4261-a20c-bef04c17b17f.mp4
- 범위를 넘어서까지 검색이 가능했습니다.
- `<` , `>` 의 터치 범위가 좁아서 클릭이 잘 안됐습니다.
- 범위 안에서만 검색이 가능하고 가능 유무에 따라 버튼 색이 달라집니다.
- padding 값을 줘서 터치 범위를 좀 넓혀줬습니다.
> DEP-331 fix: 나의 기록 이동 가능한 범위 만큼만 이동하도록 수정

- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitActivity.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step2/ChooseMateTypeActivity.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
전환 애니메이션을 없애 달라고 하셔서 없앴습니다.
버그는 아님!
> DEP-334 fix: 짝꿍 만들기 단계에서 전환 애니메이션 없애기

- dependencies.gradle
- presentation/mate/build.gradle
- presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateActivity.kt
- presentation/mate/src/main/res/layout/activity_share_mate.xml
- 인스타 공유하기 기능이 없었습니다.
- 인스타 공유하기 기능이 생겼습니다.
잘 되는데 2가지 이슈가 있습니다.
1. 안드로이드 Q 버전(= 10) 이상에서만 동작한다는 것
2. 공유하기 할 때마다 사진이 폰에 저장된다는 것
현재 방식이 사진을 저장 해놓고 그 사진의 Uri를 가져와 인스타그램에 넘기는 방식이라 그렇습니다.
만약 저장하지 않고 바로 가져다 쓸 수 있는 방법이 있으면 두 문제 다 해결될 것으로 보입니다.
이는 추후에 수정하겠습니다.
> DEP-263 feat: 인스타 스토리 공유하기 기능 구현

- presentation/policy/src/main/java/com/depromeet/threedays/policy/PolicyActivity.kt
- javascript false
- javascript true
- 어느 lint 가 xss 막으려면 js 안쓰는게 좋다고 했는데.. 일단 쓰는걸로 바꾸고 나중에 더 알아볼게요
> DEP-000 fix: webview 에서 notion 페이지 안보이는 현상 해결

- .github/workflows/deploy.yml
- build.gradle
- 버전업 커밋이 매번 추가됨
- 마지막 커밋에 버전 변경내용 추가
> DEP-000 refactor: version up commit 안보이게 변경

- .github/workflows/deploy.yml
- .github/workflows/update_version_code.yml
- deploy.yml 에서 버전 업데이트도 같이 진행함
- 배포, 버전업 동작 분리
> DEP-000 config: PR open 하면 version code 자동 변경

- .github/workflows/update_version_code.yml
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewModel.kt
- 보관된 습관 목록이 비어있어도 스낵바 노출
- 보관된 습관 목록이 비어있으면 스낵바 노출 안함
> DEP-345 fix: 보관된 습관 목록이 비어있으면 스낵바 표시안함

- .github/workflows/update_version_code.yml
- build.gradle
> DEP-000 config: 체크아웃 설정 변경

- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
- 습관이 없을 때 나의 기록 페이지 진입 시 튕겼습니다. 제가 first()랑 last()를 사용했거든요.. 👀
- 습관이 없을 때 if문 처리해서 버그 수정 했습니다.
> DEP-366 bugfix: 습관이 없을 때 나의 기록 페이지 진입 시 튕기는 버그 수정

- domain/src/main/java/com/depromeet/threedays/domain/entity/OnboardingType.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/onboarding/ReadOnboardingUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/onboarding/WriteOnboardingUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitOnboardingSnackBar.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewModel.kt
- 스낵바가 맨 위에 위치했습니다.
- 스낵바가 진입시마다 항상 보였습니다.
- x를 클릭해야 스낵바를 봤는지 유무를 저장하는 의도의 로직이 있었습니다.
- 첫 진입자인지 유무를 state로 관리했습니다.
- 스낵바가 피그마처럼 위로부터 조금 띄어지게 변경했습니다.
- 스낵바가 첫 진입자에게만 보여집니다. (습관 없을때만!)
- 스낵바를 보기만 하면 봤다고 저장하고 다음부턴 보여주지 않습니다.
- 첫 진입자인지 유무를 state로 관리하지 않습니다.
이유는 모르겠는데 padding값 줄 때 피그마랑 1대1 대응하는 값으로 넣으니 안맞더라고요..?
그래서 눈으로 봤을때 적당히 맞는 값으로 200을 주긴 했는데 추후에 확인해봐야 할 듯 합니다
> DEP-367 bugfix: 습관 보관함 스낵바 위치 수정 / 띄우는 로직 수정

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageViewModel.kt
- 로그아웃, 회원탈퇴시 로그인페이지로 이동하지 않음
- 로그아웃, 회원탈퇴시 로그인페이지로 이동함
> DEP-288 feat: 로그아웃, 회원탈퇴시 로그인페이지로 이동

- data/build.gradle
- dependencies.gradle
- presentation/mate/build.gradle
사용하지 않는 라이브러리 삭제
- facebook
- room
> DEP-000 refactor: 사용하지 않는 라이브러리 제거

- app/src/debug/res/values/strings.xml
- debug, release 앱이 아이콘, 이름 모두 같아서 헷갈림 
- debug 앱은 `짝심삼일 (debug)` 로 이름을 변경합니다
> DEP-000 refactor: debug app 이름 변경

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/res/layout/fragment_my_page.xml
- 닉네임변경, 로그아웃, 회원탈퇴 버튼 터치 영역 조정
> DEP-387 fix: 마이페이지 버튼 터치 영역 조정

- presentation/create/src/main/res/layout/activity_habit_create.xml
- presentation/create/src/main/res/layout/activity_habit_update.xml
- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
- presentation/history/src/main/java/com/depromeet/threedays/history/detail/DetailHistoryViewModel.kt
- presentation/history/src/main/res/layout/fragment_history.xml
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
- presentation/mate/src/main/res/layout/activity_set_mate_nickname.xml
- presentation/mate/src/main/res/layout/fragment_mate.xml
- 기록화면과 짝궁화면에 프로그레스바(서버 데이터 불러오는 중)을 적용했습니다.
- 상세기록 캘린더 화면 ui 오류를 수정했습니다
- 글자 수, 줄 수 제한 거는 코드를 추가했는데 왜인지 안되더라구욤...
> DEP-384 feat: 프로그레스 바 적용 및 각종 오류 수정

- presentation/splash/src/main/res/values/strings.xml
> DEP-000 refactor: Copyright 2023년으로 수정

- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
- presentation/mate/src/main/res/values/strings.xml
- 습관이 없어도 짝꿍을 만들기 페이지로 이동할 수 있었습니다.
- 습관이 없으면 다이얼로그를 띄우고 습관 만들기 페이지로 이동할 수 있도록 유도합니다.
> DEP-392 feat: 습관이 없을 때 짝꿍을 만들 수 없도록 수정
