depromeet12th/three-days-android

- .github/CODEOWNERS
- .github/workflows/build.yml
- .github/workflows/deploy.yml
- firebase app distribution 단계 추가했습니다. 
- 매 PR 변경마다 앱을 배포하는건 낭비인거같아서 develop 코드 변경될때만 배포하도록 설정했습니다
- 공용구글계정 firebase console 에서 확인하실수있어요
> DEP-35 config: firebase app distribution 추가

- core-design-system/src/main/res/drawable/bg_rect_gray_r10.xml
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/res/drawable/bg_oval_gray.xml
- presentation/home/src/main/res/drawable/bg_oval_white.xml
- presentation/home/src/main/res/drawable/bg_oval_white_stroke_blue.xml
- presentation/home/src/main/res/drawable/bg_rect_blue_r5.xml
- presentation/home/src/main/res/drawable/bg_rect_light_blue_r24.xml
- presentation/home/src/main/res/layout/fragment_home.xml
- presentation/home/src/main/res/layout/item_goal.xml
목표 목록 페이지에 해당하는 ui를
뚝딱뚝딱 만들어 봤습니다.
폰트나 색상 이런 부분에 있어서 굉장히 러프하게 짰어요.
피그마에 있는 UT 가이드가 아직 체계가 안 잡혀있는 부분이 많아서
뭐 폰트를 typography나 theme로 묶는다든지
색상마다 이름이 있어서 네이밍에 적용한다든지 이런 게 불가능 하더라구요.
나중에 수정 해야 할 것 같습니다 흑
> DEP-48 ui: 홈화면(목표 목록 페이지) 그리기

- .github/workflows/deploy.yml
- develop 코드가 변경되면 depromeet, 12기8팀 그룹 등 iOS, android 로 구분되지 않은 채 모든 테스터가 알림 메일을 받습니다. 
- develop 코드 변경시, android 테스터 그룹에만 새 앱 업로드 알림 메일이 가도록 변경합니다.
> DEP-35 config: tester 그룹 변경

- app/src/main/AndroidManifest.xml
- data/src/main/java/com/depromeet/threedays/data/mapper/GoalMapper.kt
- domain/src/main/java/com/depromeet/threedays/domain/entity/Goal.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/SimpleGoal.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/add/GoalAddActivity.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/add/GoalAddViewModel.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/update/GoalUpdateActivity.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/update/GoalUpdateViewModel.kt
- presentation/register/src/main/res/layout/activity_goal_add.xml
- presentation/register/src/main/res/layout/activity_goal_update.xml
- presentation/register/src/main/res/values/strings.xml
목표 수정 페이지가 존재하지 않았습니다.
- 목표 수정 페이지 그리기
- 목표 수정 페이지 뷰에 대한 이벤트 설정
- 로컬 디비와 연동 (데이터 불러오기 & 데이터 업데이트)
SimpleGoal을 계속 사용하는건 Goal에 대한 conflict 피해를.. 최소화하고자 일단 저렇게 해놨습니다
추후 Goal 등 확정이 되면 변경되거나 사라질 클래스입니다!
Goal에 대한 클래스나 mapper도 제가 임시로 변경한거라 언제든지 .. 변경하셔도.. 괜찮습니다!
> DEP-71 feat: 목표 수정 페이지 생성 및 기능 구현

- navigator/src/main/java/com/depromeet/threedays/navigator/GoalAddNavigator.kt
- navigator/src/main/java/com/depromeet/threedays/navigator/GoalUpdateNavigator.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/res/layout/fragment_home.xml
- presentation/register/src/main/java/com/depromeet/threedays/register/add/GoalAddModule.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/add/GoalAddNavigatorImpl.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/update/GoalUpdateModule.kt
- presentation/register/src/main/java/com/depromeet/threedays/register/update/GoalUpdateNavigatorImpl.kt
- 홈에서 목표 만들기 페이지로 이동할 수 없었습니다.
- 리스트 개수에 상관없이 항상 같은 화면이 보였습니다.
- 이제 목표 만들기 혹은 추가 버튼을 누르면 목표 만들기 페이지로 이동합니다.
- 리스트가 없을 때와 있을 때 다른 화면을 보여줍니다.
- 수정 페이지로 넘어갈 때 필요한 파일들도 추가해두었습니다. BottomSheet 완성되면 startActivity만 하면 됩니다.
> DEP-51 feature: 목표 만들기 페이지로 이동 기능 구현 (Navigator)

- app/src/main/res/values/colors.xml
- presentation/register/src/main/java/com/depromeet/threedays/register/add/GoalAddActivity.kt
- 안드로이드 기본 primary color였습니다.
- 목표 생성 화면의 데이터들이 화면이 finish 되고 다시 생성하러 들어가면 이전 데이터가 남아있었습니다.
- primary color의 값을 임시로 짝심삼일의 메인컬러로 변경했습니다. (임시)
- finish 전 해당 데이터를 null로 만들어 에러를 해결했습니다 (임시)
위 두가지 사항은 임시로 변경 & 해결 한 코드라 추후 수정 예정입니다
> DEP-90 feat:(임시) primary color 값 변경 및 목표생성화면 에러 해결

- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- 아이템을 직접 생성해야 해서 2일차까지 완료된 아이템을 테스트할 수 없었음
디자이너 분들의 요청으로 UT를 위해 버튼을 만들었습니다.
header text를 long click 하면 id가 1인 아이템을 2일차까지 완성된 아이템으로 업데이트 해줍니다.
UT가 끝난 후 삭제될 기능입니다.
> DEP-116 feat: 지정해둔 아이템을 생성하는 임시 버튼 추가

- data/src/main/java/com/depromeet/threedays/data/repository/GoalRepositoryImpl.kt
- domain/build.gradle
- domain/src/main/java/com/depromeet/threedays/domain/repository/GoalRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/GetAllGoalsUseCase.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/GoalAdapter.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
- 할일 완료를 눌러도 짝심 일수가 변하지 않았습니다.
- 리스트 변경 사항이 실시간으로 이루어지지 않아 매번 fetchGoals()를 다시 호출했습니다.
- diffUtil의 areItemsTheSame에서 객체를 비교했습니다.
- 이제 할일 완료/미완료 시 짝심 일수가 변합니다.
- 리스트 변경 사항이 실시간으로 반영됩니다.
- diffUtil의 areItemsTheSame에서 id를 비교합니다.
- flow가 dao와 viewModel에서만 사용되고 있어 실시간 반영이 되지 않았습니다.
제가 추측한 `리스트가 실시간으로 반영되지 않았던 이유`는 다음과 같습니다.
flow는 파이프와 비슷하다고 합니다.
flow를 사용하면 db에서 부터 dataSource ... presentation까지 파이프로 연결되고 데이터가 파이프를 따라 흐른다고 합니다.
데이터를 받아서 사용하는 곳에서는 이를 collect를 하여 데이터의 변동 사항이 있으면 이를 감지하고 적용할 수 있는거죠.
근데 이전에는 `flow가` dao와 viewModel에서만 사용되고 있고 `중간 구간에서 다 빠져있었습니다.`
`파이프가 중간에 끊겨져 있었기 때문에 데이터 변경을 감지하지 못했던 게` 아닐까 싶습니다.
현재는 파이프를 다 연결해두었으나, 아쉬운 점은 useCase 즉, `domain 모듈에서 flow를 사용하기 위해 coroutine 라이브러리를 사용`한다는 것인데요... 순수한 코틀린 코드만 있어야 하는 domain에서 이래도 되는 것인지...
인터넷의 다른 예제에서는 그냥 쓰긴 하던데 🤔
만약 flow를 안 쓴다면 이를 어떻게 …
> DEP-108 feat: 할일 완료/미완료 시 짝심 N일 값 변경 & flow를 사용하여 실시간 반영

- .idea/compiler.xml
- core-design-system/src/main/res/drawable/bg_rect_gray200_r10.xml
- core-design-system/src/main/res/drawable/bg_rect_gray700_r10.xml
- core-design-system/src/main/res/drawable/bg_rect_gray800_r10.xml
- core-design-system/src/main/res/drawable/bg_rect_main_r10.xml
- core-design-system/src/main/res/drawable/bg_rect_white_r18.xml
- core-design-system/src/main/res/drawable/ic_check_green.xml
- core-design-system/src/main/res/values/colors.xml
- core-design-system/src/main/res/values/typography.xml
- core/build.gradle
- core/src/main/java/com/depromeet/threedays/core/OnSingleClickListener.kt
- core/src/main/java/com/depromeet/threedays/core/extensions/Int.kt
- core/src/main/java/com/depromeet/threedays/core/extensions/PixelExt.kt
- core/src/main/java/com/depromeet/threedays/core/extensions/String.kt
- core/src/main/java/com/depromeet/threedays/core/extensions/View.kt
- core/src/main/java/com/depromeet/threedays/core/util/ThreeDaysDialogFragment.kt
- core/src/main/java/com/depromeet/threedays/core/util/ThreeDaysToast.kt
- core/src/main/res/layout/fragment_three_days_dialog.xml
- core/src/main/res/layout/toast_three_days.xml
- core/src/main/res/values/ids.xml
- core/src/main/res/values/strings.xml
- dependencies.gradle
- presentation/history/src/main/res/layout/item_objective.xml
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- dialog util이 없었습니다
- toast가 UT 기준 디자인이었습니다
- dialog를 손쉽게 띄울 수 있습니다
- toast의 디자인이 변경되고, 띄우는 시간을 (duration)을 설정할 수 있게 수정했습니다
dialog는 flag, 확인 버튼 눌렀을 때의 action을 전달하도록 했고
toast는 text를 전달하도록 했습니다.
dialog에서 title, description, emoji 등의 정보를 다 전달하지 않도록 한 이유는 정보양이 많은 것 같아서였는데,,, dialog가 계속 늘어난다면 데이터를 전달하는 방식으로 바꾸는게 좋은가? 고민이네요 (만약 같은 dialog를 여러 시점에서 호출한다면 지금의 방식이 더 편할 것 같긴합니다)
- DELETE_HABIT_NO_HISTORY
- DELETE_HABIT_WITH_HISTORY
- DELETE_HABIT_WITH_MATE
- CANCEL_HABIT_CREATE
- CANCEL_HABIT_MODIFY
- 다이얼로그 사용법
```
ThreeDaysDialogFragment.newInstance(
dialogMode = 위의 값들 중 하나,
onPositiveAction = 우측버튼 눌렀을 때 벌어질 행동에 대한 함수
).show(프래그먼트매니저(supportFragmentManager, childFragmentManager,..), ThreeDaysDialogFragment.TAG)
```
- 토스트 사용법
```
ThreeDaysToast().show(context, 표시할 문구)
```
! 스낵바는 아직 한 곳 밖에 안쓰여서 일단 안 …
> DEP-157 feat: dialog, taost util 제작

- core-design-system/src/main/res/values/themes.xml
- core/build.gradle
- core/src/main/java/com/depromeet/threedays/core/extensions/LocalTime.kt
- core/src/main/java/com/depromeet/threedays/core/util/RangeTimePickerDialogFragment.kt
- core/src/main/res/layout/fragment_range_time_picker_dialog.xml
- core/src/main/res/values/strings.xml
- presentation/create/src/main/java/com/depromeet/threedays/create/create/HabitCreateActivity.kt
- presentation/create/src/main/java/com/depromeet/threedays/create/update/HabitUpdateActivity.kt
- presentation/create/src/main/res/layout/activity_habit_create.xml
- presentation/create/src/main/res/layout/activity_habit_update.xml
- 타임피커가 없었습니다.
- 분 간격이 30인 타임피커를 제작했습니다.
- 디자인은 제가 임의로 했습니당!
> DEP-204 feat: 30분 간격인 timepicker 제작

- core-design-system/src/main/res/drawable/ic_check_small.xml
- presentation/history/src/main/res/layout/fragment_history.xml
- 스크롤 영역이 빨간색 박스 만큼으로 잡혀있었습니다.
- 이모지를 사용했습니다. (박수, 체크)
- 스크롤 영역이 파란색 만큼으로 늘어났습니다.
- NestedScrollView안에 기존 코드를 때려 넣었습니다. 변경된 코드가 많아 보이는 건 코드의 위치가 바뀌어서 그렇습니다.
- 이모지 대신 아이콘을 사용합니다. (박수, 체크)
그 외에 툴팁 쉐도우, 뷰 간의 margin 조정, 마지막 아이템 바닥과 20dp 띄우기가 적용됐습니다.
> DEP-148 ui: 나의 기록 ui 변경 사항 적용

- core/src/main/java/com/depromeet/threedays/core/util/ThreeDaysImageSnackBar.kt
- core/src/main/res/layout/image_snackbar_three_days.xml
기존의 커스텀 스낵바를 살짝 변경 시켜 만들었습니다.
하나로 통일해서 유동적으로 쓰고 싶었는데
할게 너무 많이 남아서 ㅋㅋㅋㅋㅠ 생각할 시간에 UI 하나 더 짜자 싶어서 따로 만들었습니다...
촉박하네요... 화이팅...
> DEP-195 ui: 이미지가 있는 스낵바 구현

- .github/workflows/build.yml
- .github/workflows/deploy.yml
로그가 너무 많이 남아서 빌드 실패 원인을 확인하기 어려운 현상을 해결합니다. 
- 로그가 약 13만줄 정도 남는데, 7만줄 이후는 웹페이지에서 확인이 안됨 (파일다운받아야함)
- 내용이 많고 스크롤이 길어서 페이지가 느려짐
- 로그 레벨 기본값 (lifecycle 이상)
- 수동으로 GitHub Action 트리거 못함
- 로그 레벨 변경 (build 는 warn 이상, deploy 는 error 이상만 로그 남김)
- 수동으로 GitHub Action 트리거 할 수 있음
| option | logging level | file size |
|-|-|-|
| default | >= lifecycle | 114119 |
| --warn | >= warn | 18845 |
| --quiet | >= error | 1493 | 
- 로그 파일 크기 비교해보니 `--warn` 적용하면 1/10 정도, `--quiet` 적용하면 1/100 정도 줄어드는거 확인했습니다 
- https://docs.gradle.org/current/userguide/logging.html
- https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> DEP-000 불필요한 빌드 로그 줄이기

- data/src/main/java/com/depromeet/threedays/data/api/deserializer/LocalDateDeserializer.kt
- data/src/main/java/com/depromeet/threedays/data/api/deserializer/LocalDateTimeDeserializer.kt
- data/src/main/java/com/depromeet/threedays/data/api/deserializer/LocalTimeDeserializer.kt
- data/src/main/java/com/depromeet/threedays/data/api/serializer/LocalDateSerializer.kt
- data/src/main/java/com/depromeet/threedays/data/api/serializer/LocalDateTimeSerializer.kt
- data/src/main/java/com/depromeet/threedays/data/api/serializer/LocalTimeSerializer.kt
- `yyyy-MM-dd HH:mm:ss.S`
- `yyyy-MM-dd'T'HH:mm:ss.S` 
- serialize 할 때 source 가 null 이면 `JsonNull.INSTANCE` 으로 리턴
> DEP-253 feat: 시간 자료형 직렬화 포맷 변경

- data/src/main/java/com/depromeet/threedays/data/api/MemberService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/entity/member/UpdateNicknameRequest.kt
- data/src/main/java/com/depromeet/threedays/data/repository/MemberRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/MemberRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/UpdateNicknameUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageViewModel.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/nickname/EditNicknameDialogFragment.kt
- 하드코딩된 닉네임 값을 사용했습니다. 
- 닉네임 수정 후 저장 버튼 누르면 `PATCH /api/v1/members/name` API 호출합니다
- loading, error 는 처리하지 않았습니다
> DEP-246 feat: 닉네임 수정 API 연동

- core/src/main/java/com/depromeet/threedays/core/extensions/LocalDateTime.kt
- data/src/main/java/com/depromeet/threedays/data/api/NotificationHistoryService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/NotificationHistoryRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/NotificationHistoryRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/entity/notification/NotificationHistoryReadRequest.kt
- data/src/main/java/com/depromeet/threedays/data/repository/NotificationHistoryRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/NotificationHistoryRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/notification/GetNotificationHistoriesUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/notification/MarkAsReadUseCase.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationHistoryActivity.kt
- presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationHistoryAdapter.kt
- presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationHistoryUI.kt
- presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationHistoryViewHolder.kt
- presentation/notification/src/main/java/com/depromeet/threedays/notification/NotificationHistoryViewModel.kt
- presentation/notification/src/main/res/layout/item_notification.xml
- 알림 읽음 처리 API 연동 (`PATCH /api/v1/notifications/{notificationHistoryId}`)
- 알림 시각 format 적용
- 현재시각과 비교해서 오늘 받은 알람이면 `HH:mm`, 오늘보다 전에 받은 알람이면 `yyyy.MM.dd` 로 표시
- 없습니다
> DEP-254 feat: 알림내역 읽음처리 API 연동

- data/src/main/java/com/depromeet/threedays/data/api/MemberService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/entity/member/LogoutRequest.kt
- data/src/main/java/com/depromeet/threedays/data/repository/MemberRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/MemberRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/GetMyInfoUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/LogoutUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageViewModel.kt
- presentation/mypage/src/main/res/layout/fragment_my_page.xml
- 로그아웃 API 연동 (`POST /api/v1/members/logout`)
- 저장했던 토큰(accessToken, refreshToken) 삭제, 로그아웃 성공시 로그인 페이지로 이동 필요
> DEP-248 feat: 로그아웃 API 연동

- data/src/main/java/com/depromeet/threedays/data/api/MemberService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/member/MemberRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/repository/MemberRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/MemberRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/WithdrawUseCase.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageViewModel.kt
- presentation/mypage/src/main/res/layout/fragment_my_page.xml
- 회원 탈퇴 API 연동 (`DELETE /api/v1/members`)
- 회원 탈퇴 후 토큰 삭제, 로그인페이지로 이동 필요
> DEP-249 feat: 회원탈퇴 API 연동

- presentation/splash/src/main/java/com/depromeet/threedays/splash/SplashActivity.kt
- S20 (API 31, Android 12) 에서 스플래시스크린 못넘어가고 멈추는 현상 해결
- 왜안됐는지, 왜 해결되었는지 둘 다 모르는 상태에요 ㅠ_ㅠ
> DEP-295 fix: android 12 기기에서 스플래시 스크린 멈춤 현상 해결

- .github/workflows/deploy.yml
- app/build.gradle
- 깃헙액션에서 빌드한 apk 는 카카오 sdk 사용못함
- app build.gradle 에 signingConfigs.ciDebug 추가함
- 나중에 ciRelease 도 같은 방법으로 추가 가능
- GitHub Action Secrets 에 debug.keystore 및 password 등 추가
- 카카오 키해시 등록함
> config: ci 환경에 debug keystore 추가

- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
- presentation/history/src/main/res/layout/fragment_history.xml
이건 버그라기보단 QA 기간에 나온 추가 요구사항이긴 합니다
습관이 없을 때 날짜 이동하는 뷰들을 빼달라고 해서 뺐습니다.
> DEP-322 fix: 습관이 없을 때 툴바가 가려지도록 수정

- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
온보딩 확인 여부를 다른 state와 하나의 data class로 관리했더니
update가 여러 번 되는 문제가 생기네요.
온보딩 확인 state를 별도로 분리해서 해결했습니다.
> DEP-325 fix: 짝꿍 온보딩 모달이 여러개 뜨는 버그 수정

- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryFragment.kt
- presentation/history/src/main/java/com/depromeet/threedays/history/HistoryViewModel.kt
viewModel init에서 호출하던 정보 불러오기를
fragment onresume으로 옮겨서 업데이트 되도록 했습니다.
> DEP-324 fix: 내 기록에서 습관 만들고 왔을때 화면 변화 없는 버그 수정

- presentation/history/src/main/res/layout/fragment_history.xml
- presentation/home/src/main/res/layout/bottom_sheet_noti_recommend.xml
- presentation/mate/src/main/res/layout/activity_choose_mate_type.xml
- presentation/mate/src/main/res/layout/activity_connect_habit.xml
- presentation/mate/src/main/res/layout/bottom_sheet_mate_on_boarding.xml
- presentation/mate/src/main/res/layout/fragment_mate.xml
- presentation/mypage/src/main/res/layout/activity_archived_habit.xml
- presentation/mypage/src/main/res/layout/fragment_edit_nickname_dialog.xml
- presentation/onboarding/src/main/res/layout/activity_onboarding.xml
- 버튼에 쉐도우가 들어가있었습니다.
- `android:stateListAnimator="@null"`를 사용해서 쉐도우를 전부 제거했습니다.
- 이럴 거면 혜인님처럼 걍 텍스트뷰로 할 걸...
> fix: 버튼에 들어간 쉐도우 일괄삭제

- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitAdapter.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewHolder.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewModel.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/HabitUI.kt
- presentation/mate/src/main/res/drawable/selector_gray_100_r_10_gray_200_r_10.xml
- presentation/mate/src/main/res/layout/item_connect_habit.xml
https://user-images.githubusercontent.com/76620764/210120070-98e7b877-9911-4afb-b422-2ea3d05e8922.mp4
- 두 번 선택해야 습관이 선택되는 효과가 나는 버그가 있었습니다.
- 정상 작동합니다. (영상 참고)
- 기존에는 습관이 check 상태를 들고 있으면서 관리하는 형태였는데
지금은 adapter가 관리하게 하였습니다.
또 기존의 텍스트뷰 형식을 버리고 라디오 버튼을 사용했으며
라디오 그룹으로 묶을 수 없기에 adapter가 check 상태를 관리하게 한 것입니다.
- bind 쪽에서 position을 사용하니까 경고가 뜨더라구요.
이 값이 진짜 포지션이라고 여기고 사용하지 말라면서...
아마 빠르게 스크롤 했을 때 사용자에게 보여지는 포지션과 실제 포지션의 딜레이차이 뭐 이런 거 때문에 그런거 아닐까요?...
아무튼 특정 상황이 있나봅니다. 그래서 bindingAdapterPosition을 사용했습니다.
> DEP-329 fix: 짝꿍 생성시 습관 선택이 제대로 되지 않는 버그 수정

- app/src/main/AndroidManifest.xml
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
- 2단계나 3단계에서 뒤로가기를 누르면 짝꿍 만들기 페이지 (첫 화면으로 이동했습니다)
- 2단계나 3단계에서 뒤로가기를 누르면 이전 단계로 이동합니다.
- Affinity를 사용해서 만들기 단계끼리는 새로운 Task영역에서 스택을 관리하도록 했습니다.
> fix: 짝꿍 만들기 뒤로가기시 단계 하나만 나가지도록 수정

- presentation/mate/src/main/res/layout/fragment_mate.xml
- 짝꿍이 없을 때도 툴팁, 삭제, 공유 버튼이 보였습니다.
- 짝꿍이 있을때만 버튼이 보입니다.
> DEP-333 fix: 짝꿍 없는 상태에서 툴바쪽 아이콘 일부 없애기

- data/src/main/java/com/depromeet/threedays/data/datasource/achievement/AchievementRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/achievement/AchievementRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/entity/achievement/AchievementDateEntity.kt
- data/src/main/java/com/depromeet/threedays/data/repository/AchievementRepositoryImpl.kt
습관 체크 api 요청시 사용하는 날짜 포맷을 개선합니다 
`%d-%d-%d`  (ex, 2023-1-1)
`yyyy-MM-dd`  (ex, 2023-01-01)
> DEP-000 fix: 날짜 포맷 변경

- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateImageResourceResolver.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/model/MateUI.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/share/ShareMateActivity.kt
- presentation/mypage/build.gradle
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitActivity.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/ArchivedHabitViewHolder.kt
- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/archived_habit/archived_mate/ArchivedMateUI.kt
- 레벨1 짝궁 하드코딩, 기본이미지 사용
- 레벨에 맞는 짝궁 이미지 출력
- 중복코드 제거하고싶었는데, mypage 모듈이 mate 를 의존하게되어서 좀 슬프네요.. ㅠㅠ 나중에 페이지랑 모델도 레이어를 잘 나누는 식으로 리팩터링 해보곘습니다
> DEP-285 fix: 레벨에 맞는 짝궁 이미지 출력

- presentation/history/src/main/java/com/depromeet/threedays/history/detail/DetailHistoryActivity.kt
- 캘린더에서 이전 월로 넘어가지 않았습니다
- 캘린더 스크롤 시 데이터를 새로 불러오지 않았고, 월별 통계가 표시되지 않았으며 캘린더 이동 버튼의 `enable`처리가 되지 않았습니다.
- 캘린더의 `firstMonth` 설정을 생성일로 하여 생성 월까지 넘어갈 수 있도록 하였습니다.
- 캘린더 스크롤 시 데이터를 새로 불러오고, 월별 통계가 표시되며 캘린더 이동 버튼의 `enable`처리가 됩니다
> DEP-337 fix: 캘린더에서 이전 월로 넘어가지 않는 오류 해결 및 스크롤 시 이벤트 재설정

- app/src/main/AndroidManifest.xml
- 온보딩 이후 뒤로가기하면 다시 온보딩 페이지로 이동했습니다.
- 온보딩 페이지가 스택에 쌓이지 않게 했습니다. (뒤로가기 하면 앱 그냥 종료)
> DEP-340 fix: 스플래시 온보딩 스택에 쌓이지 않도록 수정

- core-design-system/src/main/res/values/themes.xml
- presentation/home/src/main/res/layout/activity_main.xml
- bottom navigation text 사이즈가 기본값이였습니다.
- 피그마에 맞게 변경했습니다
> DEP-341 fix: bottom navigation text 사이즈 조정

- domain/src/main/java/com/depromeet/threedays/domain/entity/OnboardingType.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/onboarding/ReadOnboardingUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/onboarding/WriteOnboardingUseCase.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
- presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingViewModel.kt
- presentation/splash/src/main/java/com/depromeet/threedays/splash/SplashViewModel.kt
- 알림권유 바텀시트가 뜨지 않았습니다.
- 온보딩 key 관리를 사용하는 곳(viewModel)에서 관리했습니다.
- datastore 사용시 viewModel에서 usecase에게 key를 직접 넘겨주었습니다.
- 앱 첫 방문시 알림 권유 바텀시트가 뜹니다.
- 온보딩 key 관리를 usecase에서 관리합니다.
- datastore 사용시 viewModel에서 onboardingType을 넘겨 주어 usecase가 key를 선택하도록 합니다.
> DEP-346 feat: 알림 권유 바텀 시트 구현

- app/src/main/java/com/depromeet/threedays/firebase/FCMService.kt
- app/src/main/java/com/depromeet/threedays/firebase/FirebaseModule.kt
- app/src/main/java/com/depromeet/threedays/firebase/FirebaseTokenDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/api/NotificationTokenService.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/history/NotificationHistoryRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/history/NotificationHistoryRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/token/NotificationTokenLocalDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/token/NotificationTokenRemoteDataSource.kt
- data/src/main/java/com/depromeet/threedays/data/datasource/notification/token/NotificationTokenRemoteDataSourceImpl.kt
- data/src/main/java/com/depromeet/threedays/data/di/RemoteModule.kt
- data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
- data/src/main/java/com/depromeet/threedays/data/di/ServiceModule.kt
- data/src/main/java/com/depromeet/threedays/data/entity/notification/NotificationTokenRequest.kt
- data/src/main/java/com/depromeet/threedays/data/entity/notification/NotificationTokenResponse.kt
- data/src/main/java/com/depromeet/threedays/data/repository/DeviceUniqueIdRepositoryImpl.kt
- data/src/main/java/com/depromeet/threedays/data/repository/NotificationHistoryRepositoryImpl.kt
- data/src/main/java/com/depromeet/threedays/data/repository/NotificationTokenRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/DeviceUniqueIdRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/NotificationTokenRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/notification/token/UpdateNotificationTokenUseCase.kt
- presentation/signup/src/main/java/com/depromeet/threedays/signup/SignupActivity.kt
- presentation/signup/src/main/java/com/depromeet/threedays/signup/SignupViewModel.kt
- 회원가입 성공시 firebase registration token 을 api 서버에 등록합니다. 
- 앱 처음 설치시 `FCMService.onNewToken(String)` 콜백이 스플래시 스크린쯤에서 실행되는데, 이때는 로그인/가입 전이라 memberId 나accessToken 이 없는 상태라서.. 콜백을 제대로 사용하고 있지 않습니다. 
- FCMService 에서 usecase 를 사용하려고 inject 하려했는데 initialized 되지 않았다고 에러 발생하네요 ㅠㅠ.. 일단은 catch 로 예외 잡아서 로그만 남기게 했습니다
> DEP-357 feat: 회원가입 성공시 fcm token 등록

- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/dialog/NotiRecommendBottomSheet.kt
- StateFlow로 바텀 시트 띄워야 할 유무를 정하다 보니 바텀 시트가 중첩해서 뜨거나 백그라운드에 갔다오면 또 뜨는 버그가 있었습니다.
- SharedFlow로 관리하여 한 번만 뜨도록 했습니다.
그 외에 첫 번째 방문하는 사용자인지 검사하는 시점을 변경했습니다.
onViewCreated에서 했더니 너무 빨라서 미처 collect를 못하길래
viewModel의 init으로 옮겼습니다.
> DEP-346 feat: 알림 권유 바텀시트 로직 변경

- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/onboarding/OnBoardingBottomSheet.kt
- 함께하기 버튼을 누르면 온보딩을 종료했습니다.
- 온보딩이 중첩되는 버그가 있었습니다. (state로 관리해서)
- 함께하기 버튼을 누르면 온보딩을 종료하고 생성 페이지로 이동합니다.
- 온보딩이 중첩되지 않습니다. (state 관리 x)
> DEP-365 bugfix: 함께하기 버튼 클릭시 페이지 이동 / 중첩 버그 수정

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- presentation/splash/src/main/java/com/depromeet/threedays/splash/SplashActivity.kt
- presentation/splash/src/main/res/layout/activity_splash.xml
- 마이페이지 습관 보관함 터치가 -> 버튼에만 달려있었습니다.
- 스플래시 시간이 1초였고, 애니메이션이 끝나면 1번 더 반복하게 되어있었습니다.
- 습관보관함 터치 범위를 흰색 배경만큼 더 넓혔습니다.
- 스플래시 시간을 2초로 늘리고 반복하지 않게 변경했습니다.
- 해성님 코드를 제가 건드린거라서 확인한번만 부탁드려용
> DEP-373 마이페이지 습관 보관함 터치 영역 넓히기, 스플래시 시간 1초 추가

- app/src/main/AndroidManifest.xml
- core-design-system/src/main/res/values/themes.xml
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitActivity.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step1/ConnectHabitViewModel.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameActivity.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/create/step3/SetMateNicknameViewModel.kt
- presentation/mate/src/main/res/layout/fragment_mate.xml
- stastus bar 색상이 항상 gray 색이였습니다. gray 색이야!
- 짝꿍 만들기 과정에서 아무것도 선택하지 않고 버튼을 누르면 앱이 죽는 버그가 있었습니다. (아무도 발견 못했길래 잠수함 패치 꼬로록...)
- 특정 페이지의 status bar 색상을 흰색으로 해달라고 하셔서 변경했습니다.
- 아무것도 선택하지 않으면 버튼이 선택되지 않게 했습니다.
plugin을 설치했더니 코드 재정렬 같은 것도 같이 들어가서 변경점이 많아보이지만
헷갈릴정도는 아닌 것 같아서 냅뒀습니다.
> DEP-369 짝꿍 특정 페이지 status bar 색상 다르게 주기 / 버그 수정

- presentation/signup/src/main/java/com/depromeet/threedays/signup/SignupActivity.kt
- presentation/signup/src/main/java/com/depromeet/threedays/signup/SignupViewModel.kt
- presentation/signup/src/main/java/com/depromeet/threedays/signup/complete/SignupCompleteActivity.kt
- presentation/signup/src/main/java/com/depromeet/threedays/signup/complete/SignupCompleteViewModel.kt
- 회원가입이 끝나기 전에 fcmToken update api 를 호출하면서, 401 에러 발생함
- SignupComplete 화면에서 fcmToken 등록하게 변경
> DEP-382 fix: 회원가입과 fcmToken 등록이 동시에 실행되는 현상 해결

- presentation/mypage/src/main/java/com/depromeet/threedays/mypage/MyPageFragment.kt
- 로그아웃후 로그인페이지에 가서 뒤로 버튼을 누르면 계속 로그인 페이지로 이동함 (버그)
- 로그아웃후 로그인페이지에 가서 뒤로 버튼을 누르면 앱이 종료됨
> DEP-000 fix: 페이지 이동 후 activity 닫기

- app/build.gradle
- build-property/src/main/java/com/depromeet/threedays/buildproperty/BuildProperty.kt
- core/src/main/java/com/depromeet/threedays/core/analytics/MixpanelAnalyticsSdk.kt
- project token 값을 debug, release 동일하게 사용
- `local.properties`에 저장된 토큰 값을 읽어 debug, release 환경에 맞게 주입
- `app -> core` 방향으로 모듈이 의존하고있어서 컴파일타입에 `core` 모듈에서 `app` 모듈의 `BuildConfig` 에 접근하지 못함. 런타임에 classLoader 사용해서 `core` 모듈에서 `app` 모듈의 `BuildConfig` 클래스 접근 및 값 조회했습니다. 
- 추후 Dependnecy Injection 사용하도록 변경해서 리플렉션 없애볼게요..
> feat: mixpanel project token 환경별로 분리

- data/src/main/java/com/depromeet/threedays/data/di/RepositoryModule.kt
- data/src/main/java/com/depromeet/threedays/data/repository/LocalDataRepositoryImpl.kt
- domain/src/main/java/com/depromeet/threedays/domain/repository/LocalDataRepository.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/LogoutUseCase.kt
- domain/src/main/java/com/depromeet/threedays/domain/usecase/member/WithdrawUseCase.kt
- deviceId 하드코딩된 값 사용
- dataStore 에 저장된값 사용함
> DEP-000 fix: 로그아웃, 회원탈퇴시 앱에 저장된 데이터 모두 삭제

- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeFragment.kt
- presentation/home/src/main/java/com/depromeet/threedays/home/home/HomeViewModel.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateViewModel.kt
- collect 하는 부분에서 믹스패널 이벤트를 날려 리스트에 변화가 있을 때마다 중복된 이벤트가 발생했습니다.
- viewModel에서 response를 받는 부분에서 바로 직접 이벤트를 날립니다.
fetchGoals -> fetchHabits로 네이밍 변경 (눈에 보이길래 그냥 같이 수정했습니다)
> feature: 습관과 짝꿍 유무에 따라 믹스패널을 보내주는 위치 변경

- presentation/mate/src/main/java/com/depromeet/threedays/mate/MateFragment.kt
- presentation/mate/src/main/res/layout/fragment_mate.xml
- 짝꿍 페이지로 들어가면 다른 화면이 로딩되기 전에 말풍선이 먼저 화면에 보였습니다.
- 이제 말풍선도 다른 UI와 함께 나타납니다.
> DEP-384 feat: 말풍선만 먼저 화면에 보여지는 버그 수정

- presentation/onboarding/src/main/java/com/depromeet/threedays/onboarding/OnboardingActivity.kt
- 온보딩 인디케이터가 페이지 이동할 때마다 같이 이동하는 방식이였습니다.
- 인디케이터가 채워지는 방식으로 변경했습니다.
> DEP-401 fix: 인디케이터를 이동 방식 -> 채워가는 방식으로 변경

- core-design-system/src/main/res/values-night/themes.xml
- 다크모드로 앱에 접속하면 흰색이 검은색으로 보이고 action bar도 그대로 보였습니다.
- 다크모드를 지원하지 않게 하였습니다. (= 다크모드 선택 시 라이트모드처럼 보이게 함. 다크모드에서 action bar 없앰)
> DEP-400 ui: 다크모드 지원하지 않도록 수정
